# Header
menu: #导航栏连接
  Home: /
  API: /API    # library document reference
#  Tags: /tags
  Tools: /tools
#  Archives: /archives #/archives #归档页面URL 自定义页面标题: /自定义页面URL
  About: /about
  Github: https://github.com/SMRUCC/





rss: /atom.xml #rss地址  默认即可

#feed:
#  type: atom       #feed 类型 (atom/rss2)
#  path: /atom.xml   #rss 路径
#  limit: 20        #在 rss 中最多生成的文章数(0显示所有)


#icon http://fontawesome.io/
#首页显示
article_index:
  -  title: Easily Development
     content: Development in Visual Studio 2015 with VisualBasic.NET language, this makes much easier for both beginner and Skillful developers.
     icon: icon-book
  -  title: High performance
     content: High performance benefits from native app, batch task scheduler, programmable CLI workflow.
     icon: icon-bolt
  -  title: Easy Deployment
     content: No external dependence, no needs for solving the library dependence. Just needs install of the required version Microsoft .NET Framework.  
     icon: icon-lab
#  -  title: Github #Github
#     content: "https://github.com/SMRUCC/GCModeller/"
#     icon: icon-github-alt

# Content
excerpt_link: Read More  #阅读更多的文字显示
# fancybox: false  #开启fancybox效果 

# Miscellaneous #社交网络和统计连接地址
baidu_analytics: //hm.baidu.com/hm.js?fe2c7555911b8560db5e56121c5d5960 #百度统计
favicon: http://gcmodeller.org/DNA.png
logo: http://gcmodeller.org/DNA.png
