# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read Article
fancybox: false

# Sidebar
sidebar: 
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:

# Miscellaneous
google_analytics:
favicon: "http://gcmodeller.org/DNA.png"
twitter:
google_plus:
fb_admins: 
fb_app_id:

# scrollUp 样式
scrollUp: image

# social
social:
  github: https://github.com/SMRUCC
#  weibo: http://weibo.com/626242034